/**
 * Innledende kastemetoder scored as individually-thrown X-kast courts
 * (xkast_kongelag tables) rather than head-to-head kamper.
 */
export function isXkastMethodName(navn: string): boolean {
  const n = navn.toLowerCase();
  return (
    n.includes("x-kast") ||
    n.includes("minimatch") ||
    n.includes("halvmatch") ||
    n.includes("heilmatch")
  );
}

/**
 * Avsluttende kastemetoder scored as Kongelag courts. Mirrors
 * er_kongelag_kastemetode() in the SNC migration, which enforces the same rule
 * in the database.
 */
export function isKongelagMethodName(navn: string): boolean {
  return navn.toLowerCase().includes("kongelag");
}

/**
 * Innledende kastemetoder whose kamp generation is driven by
 * stevne.antall_runder_innl (Gloppen/NHM). X-kast methods get their omgang
 * count from kastemetode.antall_omganger instead.
 */
export function usesInitialRoundCount(navn: string): boolean {
  const n = navn.toLowerCase();
  return n.includes("gloppen") || n.includes("nordhordland");
}

/** Innledende kastemetoder generated by buildCascadeMatchups (Gloppen). */
export function isCascadeMethodName(navn: string): boolean {
  return navn.toLowerCase().includes("gloppen");
}

/**
 * Highest roundCount buildCascadeMatchups can produce without omkampar.
 *
 * The cascade is bipartite: p1 always comes from the first half of the
 * startnummer (1..m) and p2 from the second (m+1..2m), and the round number is
 * nothing but the offset between the two halves. There are only m = ceil(N/2)
 * distinct offsets, so round m+1 repeats round 1 in full — every match, just
 * dealt onto other courts. m is also the hard ceiling on how many distinct
 * opponents any one player can get, since the halves never meet internally.
 */
export function maxCascadeRounds(N: number): number {
  return Math.ceil(N / 2);
}

export function cascadeRoundLimitMessage(N: number, roundCount: number, isTeam = false): string {
  const unit = isTeam ? "par" : "spelarar";
  return (
    `Gloppen med ${N} ${unit} kan ha maks ${maxCascadeRounds(N)} rundar, ` +
    `ikkje ${roundCount} — fleire rundar gjev omkampar. ` +
    `Set ned antal rundar under Innstillingar.`
  );
}
